apiVersion: v1
kind: Service
metadata:
  name: inventory-manager-service
  namespace: inventory-manager
spec:
  type: NodePort
  selector:
    app: inventory-manager
  ports:
    - port: 8080
      targetPort: 8080
